version: "3"

services:
  ###> doctrine/doctrine-bundle ###
  db:
    container_name: database
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_HOST: db
      MYSQL_ROOT_PORT: 3306
      MYSQL_ROOT_PASSWORD: somepassword
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
  ###< doctrine/doctrine-bundle ###

  phpmyadmin:
    container_name: pma
    depends_on:
      - db
    image: phpmyadmin
    ports:
      - "8083:80"
    environment:
      PMA_HOST: db
    restart: always

  app:
    container_name: symfony-app
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8080:8000"
    depends_on:
      - db
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql://user:password@db:3306/database
    restart: always

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
